### PR TITLE
Fix documentation build failures

### PR DESCRIPTION
**Pull request by Yoshanuikabundi**
## Description
Docs seem to be failing because one of our Sphinx extensions has introduced the walrus operator (`:=`) and our docs environment is pinned to Python 3.7. Removing the pin and letting Conda choose a Python version should fix this and avoid similar issues in the future.

## Todos
Notable points that this PR has either accomplished or will accomplish.
  - [x] Unpin Python 3.7 in docs environment
  - [x] Update Versioneer to work with Python 3.12

## Status
- [x] Ready to go

### CODE REVIEW

**Comment by Yoshanuikabundi** [comment]
OK this is now at least failing for the same reason as OpenFF Units, and I think https://github.com/openforcefield/openff-sphinx-theme/pull/98 should fix that.

**Comment by Yoshanuikabundi** [comment]
I'm gonna merge this on my Monday unless someone (@mattwthompson @j-wags) objects!

**Comment by mattwthompson** [comment]
My ears are now perked up to the behavior I noticed [last night](https://github.com/openforcefield/openff-interchange/pull/830) which seems to also show up here:

> openff-fragmenter         0+untagged.1.g8616f13           dev_0    <develop>

https://github.com/openforcefield/openff-fragmenter/actions/runs/6568745094/job/17843617396?pr=170#step:6:145

**Comment by mattwthompson** [comment]
This probably fixes the docs build but I'd like to see the versioneer regression addressed

**Comment by mattwthompson** [comment]
I can't reproduce the issue locally

```shell
$ python --version && python setup.py version                                 8:28:56  ☁  Fix-docs ☀
Python 3.12.0
running version
keywords are unexpanded, not using
got version from VCS {'version': '0.2.1+5.g690547a', 'full-revisionid': '690547a4727358fd3c3fe68ac031a5904175d16a', 'dirty': False, 'error': None, 'date': '2023-10-19T01:43:35+0000'}
Version: 0.2.1+5.g690547a
 full-revisionid: 690547a4727358fd3c3fe68ac031a5904175d16a
 dirty: False
 date: 2023-10-19T01:43:35+0000

**Review by mattwthompson — APPROVED** [review]

**Pull request merged**
